name: mentz_app_challenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.5.4
  http: ^0.13.5
  flutter_map: ^0.13.1
  flutter_lints: ^2.0.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.17
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/location_2.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/google_fonts/
    - assets/icons/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/google_fonts/SpaceGrotesk.ttf
        - asset: assets/google_fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/google_fonts/SpaceGrotesk-Light.ttf
        - asset: assets/google_fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/google_fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/google_fonts/SpaceGrotesk-SemiBold.ttf

  uses-material-design: true
